import type { Plugin } from 'vite'
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { dirname, extname, join, relative } from 'node:path'

interface SvgSpriteOptions {
  iconsDir?: string
  spriteName?: string
  outputDir?: string
  dtsPath?: string
}

interface SvgIconFile {
  name: string
  content: string
}

export default function svgSprite(options: SvgSpriteOptions = {}): Plugin {
  const {
    iconsDir = 'src/assets/icons',
    spriteName = 'icons.svg',
    outputDir = 'public/images',
    dtsPath = 'src/types/icons.d.ts',
  } = options

  let config: { root: string, command: string }

  const collectIcons = (dir: string, baseDir: string = dir): SvgIconFile[] => {
    if (!statSync(dir, { throwIfNoEntry: false })?.isDirectory()) {
      return []
    }

    const icons: SvgIconFile[] = []
    const entries = readdirSync(dir, { withFileTypes: true })

    for (const entry of entries) {
      const fullPath = join(dir, entry.name)

      if (entry.isDirectory() && !entry.name.startsWith('.')) {
        icons.push(...collectIcons(fullPath, baseDir))
        continue
      }

      if (!entry.isFile() || extname(entry.name) !== '.svg') {
        continue
      }

      const relativePath = relative(baseDir, fullPath).replace(/\\/g, '/')
      const name = relativePath.replace(/\.svg$/i, '')

      icons.push({
        name,
        content: readFileSync(fullPath, 'utf-8'),
      })
    }

    return icons.sort((a, b) => a.name.localeCompare(b.name))
  }

  const createSprite = (svgFiles: SvgIconFile[]) => {
    const symbols = svgFiles.map(({ name, content }) => {
      const svgContent = content
        .replace(/<svg[^>]*>/, '')
        .replace(/<\/svg>/, '')
        .trim()

      const viewBoxMatch = content.match(/viewBox="([^"]*)"/)
      const viewBox = viewBoxMatch ? viewBoxMatch[1] : '0 0 24 24'
      const fillMatch = content.match(/fill="([^"]*)"/)
      const fillRule = fillMatch ? ` fill="${fillMatch[1]}"` : ''

      return `<symbol id="${name}" viewBox="${viewBox}"${fillRule}>${svgContent}</symbol>`
    }).join('\n\t')

    return `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
\t${symbols}
</svg>`
  }

  const createIconTypes = (svgFiles: SvgIconFile[]) => {
    const union = svgFiles.length > 0
      ? svgFiles.map(({ name }) => `'${name}'`).join(' | ')
      : 'never'

    return `/* eslint-disable */
// Generated by svg-sprite

export type IconName = ${union}
`
  }

  const writeIconTypes = (svgFiles: SvgIconFile[]) => {
    const outputPath = join(config.root, dtsPath)
    const outputDirPath = dirname(outputPath)

    if (!existsSync(outputDirPath)) {
      mkdirSync(outputDirPath, { recursive: true })
    }

    writeFileSync(outputPath, createIconTypes(svgFiles), 'utf-8')
  }

  const getIcons = () => {
    const iconsPath = join(config.root, iconsDir)

    return collectIcons(iconsPath)
  }

  const generateSpriteForServer = () => {
    try {
      const svgFiles = getIcons()

      if (svgFiles.length === 0) {
        return null
      }

      return createSprite(svgFiles)
    }
    catch (error) {
      console.warn('SVG Sprite server generation failed:', error)

      return null
    }
  }

  const generateSprite = () => {
    try {
      const svgFiles = getIcons()
      const outputPath = join(config.root, outputDir, spriteName)

      writeIconTypes(svgFiles)

      if (svgFiles.length === 0) {
        return
      }

      const sprite = createSprite(svgFiles)

      if (config.command === 'build') {
        const outputDirPath = dirname(outputPath)

        if (!existsSync(outputDirPath)) {
          mkdirSync(outputDirPath, { recursive: true })
        }

        writeFileSync(outputPath, sprite)
        console.warn(`SVG Sprite generated: ${outputPath}`)
      }
    }
    catch (error) {
      console.warn('SVG Sprite generation failed:', error)
    }
  }

  return {
    name: 'svg-sprite',
    configResolved(resolvedConfig) {
      config = resolvedConfig
    },
    configureServer(server) {
      generateSprite()

      server.middlewares.use('/images/icons.svg', (_, res, next) => {
        try {
          const sprite = generateSpriteForServer()

          if (sprite) {
            res.setHeader('Content-Type', 'image/svg+xml')
            res.setHeader('Cache-Control', 'no-cache')
            res.end(sprite)

            return
          }

          next()
        }
        catch (error) {
          console.warn('SVG Sprite server generation failed:', error)
          next()
        }
      })
    },
    buildStart() {
      generateSprite()
    },
    handleHotUpdate({ file, server }) {
      const normalizedFile = file.replace(/\\/g, '/')
      const normalizedIconsDir = iconsDir.replace(/\\/g, '/')

      if (!normalizedFile.includes(normalizedIconsDir) || extname(file) !== '.svg') {
        return
      }

      generateSprite()
      server.ws.send({ type: 'full-reload' })
    },
    generateBundle() {
      generateSprite()
    },
  }
}
