import { existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { dirname, extname, join, relative } from 'node:path'

const ICONS_DIR = 'src/assets/icons'
const DTS_PATH = 'src/types/icons.d.ts'

function collectIcons(dir: string, baseDir: string = dir): string[] {
  if (!statSync(dir, { throwIfNoEntry: false })?.isDirectory()) {
    return []
  }

  const names: string[] = []
  const entries = readdirSync(dir, { withFileTypes: true })

  for (const entry of entries) {
    const fullPath = join(dir, entry.name)

    if (entry.isDirectory() && !entry.name.startsWith('.')) {
      names.push(...collectIcons(fullPath, baseDir))
      continue
    }

    if (!entry.isFile() || extname(entry.name) !== '.svg') {
      continue
    }

    const relativePath = relative(baseDir, fullPath).replace(/\\/g, '/')
    names.push(relativePath.replace(/\.svg$/i, ''))
  }

  return names.sort((a, b) => a.localeCompare(b))
}

function createIconTypes(names: string[]) {
  const union = names.length > 0
    ? names.map(name => `'${name}'`).join(' | ')
    : 'never'

  return `/* eslint-disable */
// Generated by svg-sprite

export type IconName = ${union}
`
}

function generateIconTypes() {
  const root = process.cwd()
  const iconsPath = join(root, ICONS_DIR)
  const outputPath = join(root, DTS_PATH)
  const names = collectIcons(iconsPath)
  const outputDirPath = dirname(outputPath)

  if (!existsSync(outputDirPath)) {
    mkdirSync(outputDirPath, { recursive: true })
  }

  writeFileSync(outputPath, createIconTypes(names), 'utf-8')
}

try {
  generateIconTypes()
}
catch (error) {
  console.error('Error generating icon types:', error)
  process.exit(1)
}
